# Generated by Django 4.1.2 on 2022-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcing_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcing',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
